name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build0
      run: chmod 777 ./bin/hugo
    
    - name: Build1
      run: git submodule init && git submodule update
    
    - name: Build2
      run: ./bin/hugo -s ./blog
    
    - name: Copy CNAME
      run: cp ./CNAME ./public


