name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build0
      run: chmod 777 ./bin/hugo
    
    - name: Build1
      run: git submodule init && git submodule update
    
    - name: Build2
      run: ./bin/hugo -s ./blog
    
    - name: Copy CNAME
      run: cp ./CNAME ./public
    
    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ github.token }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: git@github.com:zhenhua32/zhenhua32.github.io.git # optional, default is 
        # Destination branch to push changes
        branch: master # optional, default is master
        # Determines if force push is used
        force: true # optional
        # Determines if --tags is used
        # Directory to change to before pushing.
        directory: ./public # optional, default is .

