name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: chmod 777 ./bin/hugo && git submodule update && ./bin/hugo -s ./blog
    
    - name: Copy CNAME
      run: copy ./CNAME ./public


